# Generated by Django 6.0.2 on 2026-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_croprecommendation_delete_cropadvice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('appointment', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
