# Generated by Django 6.0.2 on 2026-04-16 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fertilizerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('crop_year', models.IntegerField()),
                ('season', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('annual_rainfall', models.FloatField()),
                ('fertilizer', models.FloatField()),
                ('pesticide', models.FloatField()),
                ('prediction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
